version: '3.4'

services:
  airbox:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "8081:80"
      - "4430:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      #- /mnt/c/Users/${USERNAME}/Appdata/Roaming/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      #- /mnt/c/Users/${USERNAME}/Appdata/Roaming/ASP.NET/Https:/root/.aspnet/https:ro